### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by lfsantosgeo** [geojames/py_offNadir_Res#1]
Hello! I'm getting the following error when using this script:
ValueError: setting an array element with a sequence.
line 190, in graphics.
![error](https://user-images.githubusercontent.com/39103053/39782129-b0cd620a-52e7-11e8-8bd3-1118beb2e5e9.png)

**Comment by geojames** [comment]
Luiz,
I ran it on my laptop several different ways (I'm using Anaconda)
1. From Spyder IDE - Graphics will work
2. From command prompt with python - No graphics (I'll need to work on that)

The graphics are not super important, you can probably comment out line 297 and the graphics function (Lines 178-215) and it should work.

Sample Graphics:
![image](https://user-images.githubusercontent.com/10118636/39790863-f2db886e-52fd-11e8-9fba-ca5fdcf25e40.png)

![2018-05-08 20_01_32-spyder python 3 6](https://user-images.githubusercontent.com/10118636/39790324-fd90cad8-52fa-11e8-92bc-e16fa963c3da.png)

**Comment by lfsantosgeo** [comment]
Hi James!

Thank you for the reply! Actually I apologize for the issue... My CSV file had problems when it was generated. Your script is working properly as can be seen on the graphics.

![processing_ok](https://user-images.githubusercontent.com/39103053/39813537-382a7bd2-5367-11e8-9297-fc0948f4a1a1.png)
![phantom4_50m_altitude](https://user-images.githubusercontent.com/39103053/39813440-da42d7f8-5366-11e8-8ccd-f42e8656fc24.png)
